import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import '@fontsource/instrument-serif/400.css'
import '@fontsource/instrument-serif/400-italic.css'
import '@fontsource-variable/manrope'
import '@fontsource-variable/noto-sans-arabic'
import '@fontsource-variable/noto-kufi-arabic'
import LegalPage from './LegalPage'
import { I18nProvider } from './i18n'
import './start.css'
import './info-pages.css'
import './banknote-art.css'
import './i18n.css'

const type = window.location.pathname.includes('privacy') ? 'privacy' : 'terms'
createRoot(document.getElementById('root')).render(<StrictMode><I18nProvider><LegalPage type={type} /></I18nProvider></StrictMode>)
